
GNULINUX_SYSTEM_IMAGE_FILE := ArchLinuxARM-$(GNULINUX_OTA_ARCH)-latest.tar.gz
GNULINUX_SYSTEM_IMAGE_URL := https://archlinuxarm.org/os/$(GNULINUX_SYSTEM_IMAGE_FILE)

GNULINUX_CHROOT_INCLUDE_FILES := "*-$(GNULINUX_OTA_ARCH)*.xz"

