####
# Owner: hybris-device package
#
# Do not edit this file but use '.profile_user'

export PATH=/system/bin:/system/xbin
export LD_LIBRARY_PATH=/system/lib:/vendor/lib
export LD_PRELOAD=/system/lib/libc.so
export ANDROID_ROOT=/system

export PS1='(android)[\u@\h \W]\$ '

[ -f .profile_user ] && source .profile_user

